const GET_ALL_INTERNAL_EVENTS = 'GET_ALL_INTERNAL_EVENTS';

const ADD_EVENT = 'ADD_EVENT';

const DELETE_EVENT = 'DELETE_EVENT';

const UPDATE_EVENT = 'UPDATE_EVENT';

const GET_All_EXTERNAL_EVENTS = 'GET_EXTERNAL_EVENTS'