export const GET_EVENTS_BY_LOCATION = 'GET_EVENTS_BY_LOCATION';

export const GET_EVENTS_BY_CATEGORY = 'GET_EVENTS_BY_CATEGORY';

export const GET_EVENTS_BY_DATE = "GET_EVENTS_BY_DATE";

export const GET_TIX = "GET_TIX";